//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public int salesID { get; set; }
        public int productID { get; set; }
        public int customerID { get; set; }
        public string productStatus { get; set; }
        public int quantity { get; set; }
        public decimal rate { get; set; }
        public decimal totalPrice { get; set; }
        public System.DateTime purchaseDate { get; set; }
        public Nullable<int> vat { get; set; }
        public Nullable<int> discount { get; set; }
        public decimal netTotal { get; set; }
        public string transactionType { get; set; }
        public System.DateTime transactionDate { get; set; }
        public string invoiceNo { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
